name: ${project.name}
version: ${project.version}
authors: [ase34]
main: de.ase34.flyingblocksapi.FlyingBlocksPlugin
commands:
  flyingblocks-removeall:
    permission: flyingblocks.removeall
  flyingblocks-examples:
    permission: flyingblocks.examples
    usage: |
      /<command> static [<material> [<data>]]
      /<command> rising [<velocity>]
      /<command> flag [<update-frequency> [<color>]]
      /<command> sinewave [<period> [<update-frequency>]]

permissions:
  flyingblocks.removeall:
    default: op
  flyingblocks-examples:
    default: op